name: Build and Publish Docker Image

on:
  push:
    tags:
      - 'v*' 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build the Docker image
      run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/custom_nginx:${{ github.ref }} .

    - name: Push the Docker image
      run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/custom_nginx:${{ github.ref }}
